name: Publish Docker Images

on:
  push:
    branches:
      - main
    tags:
      - 'v*.*.*'
  workflow_dispatch:

permissions:
  contents: read
  packages: write
  secrets: read

jobs:
  build-and-push:
    name: Publish Docker Images
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          registry: docker.io
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ secrets.GHCR_USERNAME }}
          password: ${{ secrets.GHCR_TOKEN }}

      - name: Build and Push Tag Images
        if: ${{ startsWith(github.ref, 'refs/tags/') && secrets.GH_READ_TOKEN != '' }}
        uses: docker/build-push-action@v6
        with:
          builder: ${{ steps.buildx.outputs.name }}
          context: .
          secrets: |
            gh_read_token=${{ secrets.GH_READ_TOKEN }}
          # If we use build cache we might not be able bump to latest version installed by Dockerfile when pushing a new tag
          # cache-from: "type=registry,ref=ghcr.io/viscalyx/devshell-dsc:buildcache"
          # cache-to: "type=registry,ref=ghcr.io/viscalyx/devshell-dsc:buildcache,mode=max"
          platforms: linux/amd64,linux/arm64
          push: true
          provenance: true
          tags: |
            docker.io/viscalyx/devshell-dsc:${{ github.ref_name }}
            docker.io/viscalyx/devshell-dsc:latest
            ghcr.io/viscalyx/devshell-dsc:${{ github.ref_name }}
            ghcr.io/viscalyx/devshell-dsc:latest

      - name: Build and Push Branch Images
        if: ${{ github.ref == 'refs/heads/main' && secrets.GH_READ_TOKEN != '' }}
        uses: docker/build-push-action@v6
        with:
          builder: ${{ steps.buildx.outputs.name }}
          context: .
          secrets: |
            gh_read_token=${{ secrets.GH_READ_TOKEN }}
          # If we use build cache we might not be able bump to latest version installed by Dockerfile when pushing a new tag
          # cache-from: "type=registry,ref=ghcr.io/viscalyx/devshell-dsc:buildcache"
          # cache-to: "type=registry,ref=ghcr.io/viscalyx/devshell-dsc:buildcache,mode=max"
          platforms: linux/amd64,linux/arm64
          push: true
          provenance: true
          tags: |
            docker.io/viscalyx/devshell-dsc:${{ github.ref_name }}
            ghcr.io/viscalyx/devshell-dsc:${{ github.ref_name }}
