name: Container security (Docker Scout)

on:
  pull_request:
    branches: [ main ]
    paths:
      - '**/Dockerfile'          # rebuild only when something container‑related changes
      - '.github/workflows/**'

jobs:
  scout:
    runs-on: ubuntu-latest
    permissions:              # required for PR comments + Code‑scanning upload
      contents: read
      pull-requests: write
      security-events: write

    env:
      IMAGE_NAME: ${{ github.repository }}
      TAG: pr-${{ github.event.number }}

    steps:
      - uses: actions/checkout@v4

      - name: Set up Buildx
        uses: docker/setup-buildx-action@v3

      # If you push to Docker Hub/ghcr later, login here
      # - uses: docker/login-action@v3 …

      - name: Build image (with SBOM & provenance)
        uses: docker/build-push-action@v5
        with:
          context: .
          # single-arch only: push:false with output avoids manifest lists issue
          platforms: linux/amd64
          tags: ${{ env.IMAGE_NAME }}:${{ env.TAG }}
          sbom: mode=max              # max-mode SBOM for Scout
          provenance: mode=max        # max-mode provenance for Scout
          push: false                 # do not push
          outputs: type=oci,dest=scout-image.tar     # export single-arch OCI image to tar

      - name: Load built image into Docker
        run: docker load -i scout-image.tar

      - name: Scan local OCI archive with Docker Scout
        id: scout
        uses: docker/scout-action@v1
        with:
          command: cves           # scan local archive for CVEs
          image: oci-archive:scout-image.tar
          # --- comparison baseline  ---------------------------------------
          to-latest: true                  # “prod” == latest tag in registry
          # --- what should make the step fail -----------------------------
          only-severities: critical,high   # we tolerate ≤ medium
          exit-code: true                  # fail if *any* matching CVE left
          exit-on: vulnerability           # fail if comparison adds new vulnerabilities
          only-fixed: true                 # ignore unfixed issues
          # --- UX helpers --------------------------------------------------
          sarif-file: scout-results.sarif  # upload to Security tab
          write-comment: true              # nice PR comment
          summary: true

      - name: Upload SARIF to GitHub code-scanning
        uses: github/codeql-action/upload-sarif@v3
        with:
          sarif_file: scout-results.sarif
